### PR TITLE
Update Mandelbrot to "modern" Processing paradigm (i.e. `setup`/`draw`)

### PR DESCRIPTION
**Pull request by tildebyte**

### CODE REVIEW

**Comment by jdf** [comment]
What's wrong with a static-mode sketch? Is that deprecated now?

**Comment by GoToLoop** [comment]
i'm of the opinion that Processing modes should not depart too far from its familiarity.
Pythonian way is good for folks who already know it.
But for us Processing regulars, curious to learn about "Python Mode", too much diff. can scare us away!

**Comment by jdf** [comment]
@GoToLoop I don't understand your comment. What's different from what?

**Comment by GoToLoop** [comment]
The relocation of those global declarations are strange for other Processing modes!
Even p5.js project declares globals atop **setup()**.
Other thing strange for Processing's customs is having statements inside **setup()** but before **size()**.

**Comment by tildebyte** [comment]
I've seen issues with static-mode sketches. Given the target audience for these examples (less-experienced programmers/pythoneers/processingers), it seems like a good idea to me to stick with the "standard".

**Comment by jdf** [comment]
What sort of issues have you seen?

**Comment by tildebyte** [comment]
Hmmm. On second thought, I may have been confusing "static mode" with "doing things outside of `setup`/`draw` when one or more are already present".

**Comment by tildebyte** [comment]
However, I stand by my assertion that following the "standard" is better for novices.

**Comment by jdf** [comment]
What standard? static mode--sketches without setup() or draw()--is one of the two modes of processing.

**Comment by tildebyte** [comment]
Understood.

**Pull request closed without merging**
