### PR TITLE
created rotating Arcs example

### PR DESCRIPTION
**Pull request by prabhjotsumman**
no errors but not getting desired output

### CODE REVIEW

**Comment by jdf** [comment]
Let me know when it's ready, and I'll gladly accept it.

**Comment by GoToLoop** [comment]
@Prabhnith, it would be a great help if you also provided the link for the original Java example.

**Comment by Prabhnith** [comment]
sir this is the original file
https://github.com/processing/processing-docs/blob/master/content/examples/Demos/Graphics/RotatingArcs/RotatingArcs.pde

**Comment by GoToLoop** [comment]
I thought it'd be better to tweak the original Java Mode code before attempting to convert it to python Mode.
You can watch it online here: http://studio.ProcessingTogether.com/sp/pad/export/ro.9AqEIV-5Q9sCx
Tweaked code in the forum: https://forum.Processing.org/two/discussion/14071/converting-java-code-to-python-for-dataviz

**Comment by GoToLoop** [comment]
Finally a working Python Mode version is here. :tada:  Although it's at least 30% slower: :disappointed: 
```processing
'''
 * Rotating Arcs (v2.31)
 * by Marius Watz
 * tweaked by GoToLoop
 * 
 * Using sin/cos lookup tables, blends colors, and draws a series of
 * rotating arcs on the screen.
 *
 * GitHub.com/processing/processing-docs/blob/master/content/
 * examples/Demos/Graphics/RotatingArcs/RotatingArcs.pde
 *
 * studio.ProcessingTogether.com/sp/pad/export/ro.9AqEIV-5Q9sCx
'''

ARC_LINES, ARC_BARS, ARC_SOLIDS = 0, 2, 3
FPS, SMOOTH, NUM = 60, 2, 150

PRECISION = 1.0
LENGTH = int(360//PRECISION)
LUTS, RADS = LENGTH<<1, .5*DEG_TO_RAD*PRECISION

COS_SIN_LUTS = tuple(sin(RADS*(i-1)) if i&1 else cos(RADS*i) for i in range(LUTS))

# rotx, roty, deg, rad, w, speed
# color, render styles
pt, styles = 6*NUM * [0.0], 2*NUM * [0]

clockwise, paused = 1, False

def setup():
    size(800, 650, P3D)
    smooth(SMOOTH), frameRate(FPS), strokeWeight(1)
    initArcShapes()


def draw(idx=0):
    background(0)

    translate(width>>1, height>>1)
    rotateX(THIRD_PI * .5), rotateY(THIRD_PI * .5)

    for i in range(0, len(styles), 2):
        with pushMatrix():
            rotateX(pt[idx]), rotateY(pt[idx+1])
            pt[idx] += clockwise * pt[idx+5]      # Increase rotations
            pt[idx+1] += clockwise * pt[idx+5]*.5

            deg, rad, w = pt[idx+2], pt[idx+3], pt[idx+4]
            c, rend = styles[i], styles[i+1]

            if rend == ARC_LINES:
                stroke(c), noFill(), arcLines(0, 0, deg, rad, w)
            elif rend == ARC_BARS:
                fill(c), noStroke(), arcBars(0, 0, deg, rad, w)
            else:
                fill(c), noStroke(), arcSolids(0, 0, deg, rad, w)

        idx += 6

    frame.setTitle('FPS: %i' % round(frameRate))


def mousePressed():
    global clockwise, paused

    if   mouseButton == LEFT: clockwise *= -1
    elif mouseButton == CENTER: initArcShapes()
    else:
        paused ^= True
        noLoop() if paused else loop()


# Draw arc lines:
def arcLines(x, y, deg, rad, w):
    angs, lines = int(min(deg/PRECISION, LENGTH-1)) << 1, int(w) >> 1
    rangs, rlines = range(0, angs, 2), range(lines)

    for j in rlines:
        with beginShape():
            for i in rangs:
                vertex(x + rad*COS_SIN_LUTS[i], y + rad*COS_SIN_LUTS[i+1])
        rad += 2

# Draw arc line with bars:
def arcBars(x, y, deg, rad, w):
    angs = int(min(deg/PRECISION, LENGTH-1)) >> 1

    with beginShape(QUADS):
        for i in range(0, angs, 8):
            vertex(x + rad*COS_SIN_LUTS[i], y + rad*COS_SIN_LUTS[i+1])
            vertex(x + (rad+w)*COS_SIN_LUTS[i], y + (rad+w)*COS_SIN_LUTS[i+1])
            vertex(x + (rad+w)*COS_SIN_LUTS[i+4], y + (rad+w)*COS_SIN_LUTS[i+5])
            vertex(x + rad*COS_SIN_LUTS[i+4], y + rad*COS_SIN_LUTS[i+5])


# Draw solid arc:
def arcSolids(x, y, deg, rad, w):
    angs = int(min(deg/PRECISION, LENGTH-1)) >> 1

    with beginShape(QUAD_STRIP):
        for i in range(0, angs, 2):
            vertex(x + rad*COS_SIN_LUTS[i], y + rad*COS_SIN_LUTS[i+1])
            vertex(x + (rad+w)*COS_SIN_LUTS[i], y + (rad+w)*COS_SIN_LUTS[i+1])


# Get blend of two colors:
def blendColors(fract, r, g, b, rr, gg, bb, a=0xff):
    rr -= r
    gg -= g
    bb -= b

    return color(r + rr*fract, g + gg*fract, b + bb*fract, a)


def initArcShapes():
    for i in range(0, len(pt), 6):
        pt[i], pt[i+1] = random(TAU), random(TAU) # Random X & Y axis rotations

        # Short to quarter-circle arcs:
        pt[i+2] = 10 * int(random(8, 27)) if random(1) > .9 else random(60, 80)

        pt[i+3] = 5 * int(random(2, 50)) # Radius. Space them out nicely

        pt[i+4] = random(40, 60) if random(1) > .9 else random(4, 32) # Width of band

        pt[i+5] = DEG_TO_RAD/50 * random(5, 30) # Speed of rotation

    for i in range(0, len(styles), 2): # Get colors
        prob, rnd = random(1), random(1)

        if   prob < .3: styles[i] = blendColors(rnd, 255, 0, 100, 255, 0, 0, 210)
        elif prob < .5: styles[i] = blendColors(rnd, 200, 255, 0, 50, 120, 0, 210)
        elif prob < .7: styles[i] = blendColors(rnd, 0, 153, 255, 170, 225, 255, 210)
        elif prob < .9: styles[i] = blendColors(rnd, 200, 255, 0, 150, 255, 0, 210)
        else:           styles[i] = 0xdcFFFFFF

        styles[i+1] = int(random(3)) # Pick arc style
```

**Pull request closed without merging**
