### PR TITLE
Added loop to get JNI library dependencies. Fix Processing.py-Bugs#307

### PR DESCRIPTION
**Pull request by mpsftw**
add_library would fail when more than one native library was present and
dependencies existed. This change goes through all permutations to find
a load order that satisfies dependencies. n! permutations is
unrealistic, so I added an arbitrary stop at 4096. That should be more
than enough to find most dependencies most of the time.

### CODE REVIEW

**Comment by jdf** [comment]
I think the correct fix is to add the directory containing the DLLs to `java.library.path` and then use `System.loadLibrary()` (*not* `System.load()`) on each in any order

**Comment by mpsftw** [comment]
I agree, but modifying java.library.path doesn't work anymore. That's actually still in the code (it happens on line 191), java just won't do it anymore.

**Comment by mpsftw** [comment]
Yeah, I just checked and loadLibrary only recognises the java.library.path specified on the command line. It doesn't work to modify it programatically. Swapping load() for loadLibrary() fails to find the native libraries on my JVM (build 1.8.0_202-b08). I don't know when it stopped doing that, but it's the core issue behind all the add_library problems.

**Comment by mpsftw** [comment]
I could switch it to use load() as a fallback to loadLibrary(). I tested that and it works.

**Review by jdf — APPROVED** [review]

**Pull request merged**
