### PR TITLE
Implement Spore1 and Spore2 examples

### PR DESCRIPTION
**Pull request by berinhard**
Both examples were only implemented in Java. This PR adds their respective python versions.

### CODE REVIEW

**Comment by berinhard** [comment]
Since this was my first port from Java to Python, I was very respectful with the original code decisions. The Python version ended up as being only a copy from the Java version, even though the code is not good.

The thing is, after  talking with @villares about the Java code and its problems, I started to think if this porting work should respect only the visual result from the example. At the spore examples, I really think there is a **way** more pythonic solution that stills being readable and usable as an example of a cellular automaton implementation.

@jdf what do you think about this? Should I try to adapt the Java code to Python as it is or should the python examples have a more pythonic implementation?

**Comment by jdf** [comment]
I would very much prefer Pythonic solutions, as long as they're not "too clever".

**Comment by berinhard** [comment]
@jdf I'm really without too much free time on my hand right now, so this refactoring is waiting too long. Maybe we could merge it and leave the refactoring for the future?

**Comment by jdf** [comment]
With all due gratitude, I don't think these should be used as examples.

**Comment by berinhard** [comment]
@jdf I partially agree with you. The part that I agree is that this code is not ideal and neither its Java implementation is. This is why I think this is a bad example, but it still being an example. The part that I disagree is that I think processing.py examples should mirror the Java ones for the sake of consistency between both examples library. 

But, honestly, I'll leave it up to you. Feel free to close or merge this PR :+1:

**Pull request closed without merging**
