### PR TITLE
Integration with Processing 3.0.1

### PR DESCRIPTION
**Pull request by Luxapodular**

### CODE REVIEW

**Comment by jdf** [comment]
All right; here we go!

**Comment by p5k12** [comment]
Hi,  Thanks so much for making this.  I use processing.py every day with my
students but I don't understand what you guys are up to.  Hopeful about you
writing "Here we go" ?  Is there some alpha or beta version to test?

All right; here we go!

—
Reply to this email directly or view it on GitHub
<https://github.com/jdf/processing.py/pull/159#issuecomment-150975174>.

**Comment by tildebyte** [comment]
@p5k12 Luxapodular is doing work to get Processing.py working with (the latest cutting-edge) Processing 3.x

**Comment by p5k12** [comment]
Thanks again!  I realize that.     But nothing is usable yet, right?  The
"here we go" marks the start of a push to get that done?

**Comment by tildebyte** [comment]
@p5k12 I believe that that is accurate. I'm going to pull and try to build, probably sometime tonight, to see if it's generally usable (or even buildable ;) ).

**Comment by p5k12** [comment]
Thanks

**Comment by jdf** [comment]
That's right. As far as I know, the unit tests don't even pass, which is a
minimal first step to evaluating where we're at.

On Sun, Oct 25, 2015 at 5:48 PM, Mark Sawula <notifications@github.com>
wrote:

> Thanks again! I realize that. But nothing is usable yet, right? The
> "here we go" marks the start of a push to get that done?
> On Oct 25, 2015 5:45 PM, "tildebyte" <notifications@github.com> wrote:
>
> > @p5k12 <https://github.com/p5k12> Luxapodular is doing work to get
> > Processing.py working with (the latest cutting-edge) Processing 3.x
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jdf/processing.py/pull/159#issuecomment-150977134>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jdf/processing.py/pull/159#issuecomment-150977278>.
>



-- 
Jonathan Feinberg  jdf@pobox.com  http://MrFeinberg.com/

**Comment by tildebyte** [comment]
Not really sure how to proceed with feedback, but assuming that this isn't the *best* place;
Mode and standalone build and run some sketches just fine.
@Luxapodular : I'm seeing `processing.app.SketchException: AttributeError: '_ast.Attribute' object has no attribute 'id'` with some sketches. Is this a known issue, or would you like more detail?

**Comment by Luxapodular** [comment]
Detail would be greatly appreciated! Just file it under issues and we'll check it out.

**Pull request merged**
