### PR TITLE
Add processing 3.5.3 new methods

### LINKED ISSUE #336: Support new methods circle, square, push and pop
Processing 3.5.3 added [4 new methods](https://github.com/processing/processing/blob/master/build/shared/revisions.txt#L31) to its API: `circle`, `square`, `push` and `pop` and they aren't available in the current version of processing.py.

I was looking at the code and I don't know if I'm being naive, but it seemed to me that it's just a matter of adding those methods [to this line](https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/core.py#L260), since none of the new method are Python reserved words.

@jdf is this approach reasonable? I fell like there's also some Java code to be added somewhere, but I'm not that familiar with Jython. Let me know if and how I can help with that. Thanks!

### PR DESCRIPTION
**Pull request by berinhard**
Fixes #336 

This PR add the new methods added by Processing 3.5.3 and also enable the use of `push` and `pop` as context managers.

I struggled with the build process, but I wasn't successful. I'm always running into this error:

```
BUILD FAILED
/home/bernardo/workspace/processing.py/build.xml:216: The following error occurred while executing this line:
/home/bernardo/workspace/processing/build/build.xml:57: Unsupported Java version: 10.0.2. To build, make sure that Java 8 (aka Java 1.8) is installed.
```

Even though I have Java 8 installed and my `JAVA_HOME` env var set to use my Java 8 installation. I'm not that familiar with Java and a lot of posts I read on Stackoverflow suggests me to use an IDE to build instead of the command line.

### CODE REVIEW

**Comment by jdf** [comment]
Could you add a test that exercise push() and pop()? I don't even know what they do. :)

**Comment by jdf** [comment]
I'm guessing there's a java 10 in your $PATH.

**Comment by berinhard** [comment]
@jdf PR updated =]

I added new tests for the `circle` method and also for the `push`/`pop` as well. They're passing for me as you can see in this print:

screenshot from 2019-02-07 13-24-31

I also have a question. Should I also add those new methods to the [`keywords.txt` file](https://github.com/jdf/processing.py/blob/0f09f2d39b015b5813b22c999c3fda8faa58fcf0/mode/keywords.txt#L639)?

**Comment by jdf** [comment]
Nice work; thank you.

**Comment by jdf** [comment]
Oops; missed your question. Yes, it would be great to have new keyword lighlighting too.

**Pull request merged**
